### ISSUE TITLE
SubscribeAsync Can't  received message 

### ISSUE THREAD

**Issue by springe2004** [tautvydasversockas/cqrs-eventsourcing#3]
I ran the example, but the subscription didn't receive the message

**Comment by tautvydasversockas** [comment]
@springe2004 have you successfully ran the code via Docker Compose? If so, have you created any events (i.e. created an account)?

**Comment by tautvydasversockas** [comment]
@springe2004 moreover, you need to create an EventStoreDB persistent subscription manually first by going to EventStore persistent subscription dashboard (http://localhost:2113). I will write a readme file later.
![image](https://user-images.githubusercontent.com/12632820/104017190-56659280-51c0-11eb-9e1a-0ea5414df7c2.png)
![image](https://user-images.githubusercontent.com/12632820/104017243-709f7080-51c0-11eb-807f-77bc1a63ba15.png)

**Comment by tautvydasversockas** [comment]
Closed due to inactivity.
